__include__: [ './dfine-ssdd.yml', '../base/deim.yml' ]

output_dir: ./deim_outputs/id-7M-B1-C-180epoch

# ---- 优化器（稳健）----
optimizer:
  type: AdamW
  params:
    - { params: '^(?=.*backbone)(?!.*(norm|bn)).*$', lr: 0.00030 }
    - { params: '^(?=.*backbone)(?=.*(norm|bn)).*$', lr: 0.00030, weight_decay: 0.0 }
    - { params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn|bias)).*$', weight_decay: 0.0 }
  lr: 0.00060
  betas: [0.9, 0.98]
  weight_decay: 0.00050

# ---- 调度策略（更平滑）----
epoches: 200
lrsheduler: multistep
lr_gamma: 0.5
milestones: [120, 170, 190]
no_aug_epoch: 10
warmup_iter: 1200

# ---- 数据增强（保守）----
train_dataloader:
  dataset:
    transforms:
      mosaic_prob: 0.40
      policy:
        epoch: [40, 100, 150]
  collate_fn:
    mixup_epochs: [4, 60]
    stop_epoch: 170
    ema_restart_decay: 0.99990
    base_size_repeat: 1

# ---- 训练策略增强 ----
use_amp: true
sync_bn: true
clip_max_norm: 1.0

# ---- 损失权重调整 ----
DEIMCriterion:
  weight_dict:
    loss_vfl: 1.0
    loss_bbox: 5.0
    loss_giou: 2.0
    loss_fgl: 0.1
    loss_ddf: 1.0
    loss_mal: 0.8

# 模型配置保持不变（删除 c_mid 以避免报错，不影响模型规模/GFLOPs）
HGNetv2:
  name: 'B1'
  return_idx: [2, 3]
  pretrained: False

HybridEncoder:
  in_channels: [320, 320]
