__include__: [ './dfine-ssdd.yml', '../base/deim.yml' ]

output_dir: ./deim_outputs/SSDD-2.13-2

# ---- 优化器（略更积极）----
optimizer:
  type: AdamW
  params:
    - { params: '^(?=.*backbone)(?!.*(norm|bn)).*$', lr: 0.00035 }
    - { params: '^(?=.*backbone)(?=.*(norm|bn)).*$', lr: 0.00035, weight_decay: 0.0 }
    - { params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn|bias)).*$', weight_decay: 0.0 }
  lr: 0.00075
  betas: [0.9, 0.96]
  weight_decay: 0.00020

# ---- 调度策略（细粒度）----
epoches: 160
lrsheduler: multistep
lr_gamma: 0.5
milestones: [110, 160, 190]
no_aug_epoch: 12
warmup_iter: 1400

# ---- 数据增强（前强后收）----
train_dataloader:
  dataset:
    transforms:
      mosaic_prob: 0.50
      policy:
        epoch: [30, 80, 140]
  collate_fn:
    mixup_epochs: [4, 80]
    stop_epoch: 180
    ema_restart_decay: 0.99990
    base_size_repeat: 1

# ---- 训练策略增强 ----
use_amp: true
sync_bn: true
clip_max_norm: 1.0

# ---- 损失权重调整 ----
DEIMCriterion:
  weight_dict:
    loss_vfl: 1.1
    loss_bbox: 5.5
    loss_giou: 2.2
    loss_fgl: 0.1
    loss_ddf: 1.0
    loss_mal: 0.8
    
DEIM:
  c_mid: 320
# 模型配置保持不变（删除 c_mid 以避免报错，不影响模型规模/GFLOPs）
HGNetv2:
  name: 'B1'
  return_idx: [2, 3]
  pretrained: False

HybridEncoder:
  in_channels: [320, 320]
