__include__: [ './dfine-ssdd.yml', '../base/deim.yml' ]

output_dir: ./deim_outputs/id-7M-B1-C-180epoch

# ---- 优化器（激进但控稳）----
optimizer:
  type: AdamW
  params:
    - { params: '^(?=.*backbone)(?!.*(norm|bn)).*$', lr: 0.00040 }
    - { params: '^(?=.*backbone)(?=.*(norm|bn)).*$', lr: 0.00040, weight_decay: 0.0 }
    - { params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn|bias)).*$', weight_decay: 0.0 }
  lr: 0.00085
  betas: [0.9, 0.94]
  weight_decay: 0.00010

# ---- 调度策略（错峰到末段）----
epoches: 200
lrsheduler: multistep
lr_gamma: 0.5
milestones: [120, 170, 195]
no_aug_epoch: 15
warmup_iter: 1500

# ---- 数据增强（更强，错峰）----
train_dataloader:
  dataset:
    transforms:
      mosaic_prob: 0.60
      policy:
        epoch: [40, 110, 170]
  collate_fn:
    mixup_epochs: [20, 100]
    stop_epoch: 190
    ema_restart_decay: 0.99995
    base_size_repeat: 1

# ---- 训练策略增强 ----
use_amp: true
sync_bn: true
clip_max_norm: 1.0

# ---- 损失权重调整（略加强回归）----
DEIMCriterion:
  weight_dict:
    loss_vfl: 1.2
    loss_bbox: 6.0
    loss_giou: 2.5
    loss_fgl: 0.1
    loss_ddf: 1.0
    loss_mal: 0.8

DEIM:
  c_mid: 320
# 模型配置保持不变（删除 c_mid 以避免报错，不影响模型规模/GFLOPs）
HGNetv2:
  name: 'B1'
  return_idx: [2, 3]
  pretrained: False

HybridEncoder:
  in_channels: [320, 320]
